# Generated by Django 5.2.16 on 2026-07-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable internal identifier for this reader device.', max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('receiving', 'Receiving'), ('dispatch', 'Dispatch')], max_length=16)),
                ('enabled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
    ]
