# Generated by Django 5.2.16 on 2026-07-16 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawRFIDEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reader_event_key', models.CharField(max_length=128)),
                ('epc', models.CharField(blank=True, max_length=128)),
                ('raw_payload', models.TextField()),
                ('queue_state', models.CharField(choices=[('unassigned', 'Unassigned'), ('queued', 'Queued'), ('inflight', 'Inflight'), ('retry', 'Retry'), ('sent', 'Sent'), ('rejected', 'Rejected'), ('dead', 'Dead')], default='unassigned', max_length=16)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_events', to='bridge_core.readerdevice')),
            ],
            options={
                'ordering': ('received_at', 'id'),
                'indexes': [models.Index(fields=['queue_state', 'received_at'], name='rfid_event_queue_received_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'reader_event_key'), name='unique_reader_event_key_per_device')],
            },
        ),
    ]
