# Generated by Django 5.2.16 on 2026-07-16 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_core', '0002_rawrfidevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('outcome', models.CharField(choices=[('started', 'Started'), ('sent', 'Sent'), ('retry', 'Retry'), ('rejected', 'Rejected'), ('dead', 'Dead')], default='started', max_length=16)),
                ('response_code', models.CharField(blank=True, max_length=64)),
                ('error_kind', models.CharField(blank=True, max_length=128)),
                ('detail', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='bridge_core.rawrfidevent')),
            ],
            options={
                'ordering': ('event_id', 'attempt_number'),
                'indexes': [models.Index(fields=['outcome', 'attempted_at'], name='delivery_outcome_attempted_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'attempt_number'), name='unique_delivery_attempt_number_per_event')],
            },
        ),
    ]
