# Generated by Django 5.2.16 on 2026-07-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_core', '0003_deliveryattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(default='default', help_text='Stable identifier for this non-secret configuration.', max_length=64, unique=True)),
                ('worker_batch_size', models.PositiveIntegerField(default=50)),
                ('max_delivery_attempts', models.PositiveIntegerField(default=10)),
                ('retry_initial_seconds', models.PositiveIntegerField(default=30)),
                ('retry_max_seconds', models.PositiveIntegerField(default=3600)),
                ('event_retention_days', models.PositiveIntegerField(default=90)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operational configuration',
                'verbose_name_plural': 'Operational configurations',
                'ordering': ('name',),
            },
        ),
    ]
