# Generated by Django 5.2.16 on 2026-07-17 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_core', '0005_seed_default_operational_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_session_key', models.CharField(help_text='Opaque session identifier supplied by the controlling system.', max_length=128, unique=True)),
                ('operation_type', models.CharField(choices=[('receipt', 'Receipt'), ('dispatch', 'Dispatch')], max_length=16)),
                ('odoo_model', models.CharField(default='stock.picking', max_length=64)),
                ('odoo_record_id', models.PositiveBigIntegerField()),
                ('odoo_reference', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfid_sessions', to='bridge_core.readerdevice')),
            ],
            options={
                'ordering': ('-opened_at', '-id'),
                'indexes': [models.Index(fields=['status', 'opened_at'], name='rfid_session_status_opened_idx'), models.Index(fields=['odoo_model', 'odoo_record_id'], name='rfid_session_odoo_record_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('device',), name='unique_active_rfid_session_per_device')],
            },
        ),
    ]
