# Generated by Django 5.2.16 on 2026-07-17 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_core', '0006_rfidsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawrfidevent',
            name='rfid_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_events', to='bridge_core.rfidsession'),
        ),
    ]
