# Generated by Django 5.2.16 on 2026-07-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_core', '0007_rawrfidevent_rfid_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='readerdevice',
            name='connect_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='readerdevice',
            name='device_address',
            field=models.PositiveSmallIntegerField(default=1, help_text='Reader protocol device address.'),
        ),
        migrations.AddField(
            model_name='readerdevice',
            name='host',
            field=models.CharField(blank=True, help_text='Reader hostname or IP address.', max_length=255),
        ),
        migrations.AddField(
            model_name='readerdevice',
            name='inventory_mode',
            field=models.CharField(choices=[('cached', 'Cached inventory'), ('active', 'Active reporting')], default='cached', max_length=16),
        ),
        migrations.AddField(
            model_name='readerdevice',
            name='port',
            field=models.PositiveIntegerField(default=8090, help_text='Reader TCP port.'),
        ),
        migrations.AddField(
            model_name='readerdevice',
            name='read_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='readerdevice',
            name='reconnect_delay_seconds',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
