# Generated by Django 5.2.16 on 2026-07-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_core', '0008_readerdevice_connect_timeout_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalconfiguration',
            name='odoo_authentication_method',
            field=models.CharField(choices=[('none', 'No authentication'), ('bearer_token', 'Bearer token'), ('basic', 'Username and secret'), ('api_key', 'API key')], default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='operationalconfiguration',
            name='odoo_base_url',
            field=models.URLField(blank=True, help_text='Base URL of the approved Odoo.sh environment.', max_length=500),
        ),
        migrations.AddField(
            model_name='operationalconfiguration',
            name='odoo_client_identifier',
            field=models.CharField(blank=True, help_text='Username, client ID, or integration identifier.', max_length=255),
        ),
        migrations.AddField(
            model_name='operationalconfiguration',
            name='odoo_database',
            field=models.CharField(blank=True, help_text='Optional Odoo database or environment identifier.', max_length=255),
        ),
        migrations.AddField(
            model_name='operationalconfiguration',
            name='odoo_event_endpoint',
            field=models.CharField(blank=True, help_text='Relative or absolute RFID event endpoint.', max_length=500),
        ),
        migrations.AddField(
            model_name='operationalconfiguration',
            name='odoo_integration_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationalconfiguration',
            name='odoo_request_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='operationalconfiguration',
            name='odoo_secret_encrypted',
            field=models.TextField(blank=True, editable=False, help_text='Encrypted Odoo integration credential.'),
        ),
        migrations.AddField(
            model_name='operationalconfiguration',
            name='odoo_session_endpoint',
            field=models.CharField(blank=True, help_text='Relative or absolute RFID session endpoint.', max_length=500),
        ),
        migrations.AddField(
            model_name='operationalconfiguration',
            name='odoo_verify_tls',
            field=models.BooleanField(default=True),
        ),
    ]
