# Generated by Django 5.2.16 on 2026-07-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_core', '0009_operationalconfiguration_odoo_authentication_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalconfiguration',
            name='odoo_inventory_count_endpoint',
            field=models.CharField(blank=True, default='/api/rfid/inventory_count', help_text='Temporary POC endpoint that accepts location_id and rfid_tags.', max_length=500),
        ),
        migrations.AddField(
            model_name='operationalconfiguration',
            name='odoo_inventory_count_location_id',
            field=models.PositiveIntegerField(blank=True, help_text='Odoo staging stock.location record ID used only by the inventory-count POC.', null=True),
        ),
        migrations.AddField(
            model_name='operationalconfiguration',
            name='odoo_inventory_count_poc_enabled',
            field=models.BooleanField(default=False, help_text='Enable the temporary Bhumika inventory-count proof of concept configuration.'),
        ),
        migrations.AlterField(
            model_name='operationalconfiguration',
            name='odoo_authentication_method',
            field=models.CharField(choices=[('none', 'No authentication'), ('bearer_token', 'Bearer token'), ('basic', 'Username and secret'), ('api_key', 'API key'), ('odoo_session', 'Odoo username and password session')], default='none', max_length=32),
        ),
    ]
