# Generated by Django 5.2.16 on 2026-07-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_core', '0010_add_inventory_count_poc_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalconfiguration',
            name='poc_allow_odoo_contact',
            field=models.BooleanField(default=False, help_text='Allow controlled staff-only POC actions to contact the configured Odoo staging database.'),
        ),
        migrations.AddField(
            model_name='operationalconfiguration',
            name='poc_allow_physical_reader_contact',
            field=models.BooleanField(default=False, help_text='Allow controlled staff-only POC actions to contact configured RFID readers.'),
        ),
        migrations.AddField(
            model_name='operationalconfiguration',
            name='poc_reader_backend',
            field=models.CharField(choices=[('fake', 'Fake reader'), ('cached_tcp', 'Cached TCP reader')], default='fake', help_text='Reader backend used by controlled staff-only POC actions.', max_length=32),
        ),
    ]
