# Generated by Django 5.2.16 on 2026-07-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_core', '0011_add_poc_runtime_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalconfiguration',
            name='setup_completed',
            field=models.BooleanField(default=False, help_text='Indicates whether the initial deployment wizard has been completed.'),
        ),
        migrations.AddField(
            model_name='operationalconfiguration',
            name='setup_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the initial deployment wizard was completed.', null=True),
        ),
    ]
