# Generated by Django 5.2.16 on 2026-07-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_core', '0012_operationalconfiguration_setup_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalconfiguration',
            name='odoo_inventory_count_endpoint',
            field=models.CharField(blank=True, default='/api/rfid/inventory_count', help_text='Validation endpoint that accepts location_id and rfid_tags.', max_length=500),
        ),
        migrations.AlterField(
            model_name='operationalconfiguration',
            name='odoo_inventory_count_poc_enabled',
            field=models.BooleanField(default=False, help_text='Enable the temporary inventory validation proof of concept configuration.'),
        ),
        migrations.AlterField(
            model_name='operationalconfiguration',
            name='poc_allow_odoo_contact',
            field=models.BooleanField(default=False, help_text='Allow controlled configuration actions to contact the configured Odoo staging database.'),
        ),
        migrations.AlterField(
            model_name='operationalconfiguration',
            name='poc_allow_physical_reader_contact',
            field=models.BooleanField(default=False, help_text='Allow controlled configuration actions to contact configured RFID readers.'),
        ),
        migrations.AlterField(
            model_name='operationalconfiguration',
            name='poc_reader_backend',
            field=models.CharField(choices=[('fake', 'Fake reader'), ('cached_tcp', 'Cached TCP reader')], default='fake', help_text='Reader backend used by controlled configuration actions.', max_length=32),
        ),
    ]
