# Generated by Django 5.2.16 on 2026-08-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_core', '0013_alter_operationalconfiguration_odoo_inventory_count_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalconfiguration',
            name='poc_reader_backend',
            field=models.CharField(choices=[('fake', 'Fake reader'), ('cached_tcp', 'Cached TCP reader'), ('active_tcp', 'Active TCP reader')], default='fake', help_text='Reader backend used by controlled configuration actions.', max_length=32),
        ),
    ]
