"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from .environment import load_configuration, require_bool, require_value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CONFIGURATION = load_configuration()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = require_value(CONFIGURATION, "DJANGO_SECRET_KEY")
ODOO_CREDENTIAL_ENCRYPTION_KEY = require_value(
    CONFIGURATION,
    "ODOO_CREDENTIAL_ENCRYPTION_KEY",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = require_bool(CONFIGURATION, "DJANGO_DEBUG")

ALLOWED_HOSTS = [
    host.strip()
    for host in require_value(
        CONFIGURATION,
        "DJANGO_ALLOWED_HOSTS",
    ).split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    f"http://{host}"
    for host in ALLOWED_HOSTS
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bridge_core.apps.BridgeCoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'bridge_core.middleware.RequireInitialAdminPasswordChangeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": require_value(CONFIGURATION, "POSTGRES_DB"),
        "USER": require_value(CONFIGURATION, "POSTGRES_USER"),
        "PASSWORD": require_value(CONFIGURATION, "POSTGRES_PASSWORD"),
        "HOST": require_value(CONFIGURATION, "POSTGRES_HOST"),
        "PORT": require_value(CONFIGURATION, "POSTGRES_PORT"),
        "CONN_MAX_AGE": 0,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = require_value(CONFIGURATION, "DJANGO_TIME_ZONE")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = Path("/var/lib/rfid_bridge/staticfiles")

READER_BACKEND = require_value(CONFIGURATION, "READER_BACKEND")
SENDER_BACKEND = require_value(CONFIGURATION, "SENDER_BACKEND")
ALLOW_PHYSICAL_READER_CONTACT = require_bool(
    CONFIGURATION,
    "ALLOW_PHYSICAL_READER_CONTACT",
)
ALLOW_ODOO_CONTACT = require_bool(CONFIGURATION, "ALLOW_ODOO_CONTACT")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "bridge_core:dashboard"
LOGOUT_REDIRECT_URL = "login"
